name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/swagger.json'
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the docs
        if: github.event.action != 'closed'
        run: |
          yarn add @redocly/cli
          yarn redocly build-docs ./docs/swagger.json --output ./docs/index.html
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto